### ISSUE TITLE
Buttons active state

### ISSUE THREAD

**Issue by soyuka** [zurb/foundation#5249]
Why do foundation do not have any active state on buttons?

Is this a design choice? I could make a PR for this by adding a class to the https://github.com/zurb/foundation/blob/master/scss/foundation/components/_buttons.scss#L134 file, but I want to know if this would be appreciated or not.

It's really anoying to replace this as there is no way to replace the `button-style` mixin without creating a new one (and so a new `button` mixin etc.). 

Workaround at the moment:
```scss
.button.active { background-color: scale-color($primary-color, $lightness: $button-function-factor); }
.button.secondary.active { background-color: scale-color($secondary-color, $lightness: $button-function-factor); }
.button.success.active { background-color: scale-color($success-color, $lightness: $button-function-factor); }
.button.alert.active { background-color: scale-color($alert-color, $lightness: $button-function-factor); }
``` 
Thanks.
