### ISSUE TITLE
Off Canvas Back-Link Overlay Transition doesn't work in Safari

### ISSUE THREAD

**Issue by karlertl** [zurb/foundation#5332]
In 5.2.3, the off canvas back-link overlay should fade in within 300 ms:
```css
.move-right .exit-off-canvas {
	...
	transition: background 300ms ease;
	...
}
```
This background transition doesn't work in Safari. The overlay appears suddenly and without any background transition. I tested this in Safari 7 (OS X) and Mobile Safari (iPhone 4/iOS 7).
