### ISSUE TITLE
Interchange + Layout switching on Tablets

### ISSUE THREAD

**Issue by doertedev** [zurb/foundation#5821]
I devved a site, with a background-image container interchanged right between body and /body:

```html
<body>
    <div id="bgcontainer" 
            data-interchange="[/files/layout/bg_1000.png,(only screen and (min-width: 900px))],
                              [/files/layout/bg_1200.png,(only screen and (min-width: 1150px))],
                              [/files/layout/bg_1600.png,(only screen and (min-width: 1550px))]">
    </div>
</body>
``` 

Then, for JS screwups + tin foil heads I added some css to load depending on the available min-width:

```scss

#bgcontainer
{
    width: 100%;
    height: 100%;
    background-repeat: no-repeat;
    background-position: top left;
    background-attachment: fixed;
    background-size: 100%;
    overflow-y: scroll;
    overflow-x: hidden;
    @media(only screen and min-width: 900px) {

        background-image: url('/files/layout/bg_1000.png');
    }
    @media(only screen and min-width: 1150px) {

        background-image: url('/files/layout/bg_1200.png');
    }
    @media(only screen and min-width: 1550px) {

        background-image: url('/files/layout/bg_1600.png');
    }
}
```

But now comes the ipad 3 / Galaxy node pro 12.1 screwup when flipping the device:

*Agile foo:*
As the site's visitor, when changing the perspective from horizontal to vertical, I expect the background image to either resize or disappear because the min-width is not longer valid. Secondary sounds more reasonable. 

*Expected behaviour:*
The perspective is changed, and the horizontal background image displays in filling 100% of the page's height. Or not at all, as mentioned above.

*Actual result:*
The horizontal background image displays in filling only 50% of the pages height.

Now that the docs only mention "replace" as an interchange container's available events, we either have to fix this or make the user aware then when a perspective is being changed certain js commands have to be set. Either way, awesome module!

_tested in android: ff + chrome @ latest + ios: safari + chrome @ latest_
