### ISSUE TITLE
Custom download uses em for padding instead of rem

### ISSUE THREAD

**Issue by bryanforbes** [zurb/foundation#5838]
When doing a custom download, there is no way to get a build with the `columns` class the same as the "everything" or "essential" download. Both of those have the following for the `columns` definition:

```css
  .column,
  .columns {
    position: relative;
    padding-left: 0.9375rem;
    padding-right: 0.9375rem;
    float: left; }
```

However, when generating a custom download, the following is generated:

```css
  .column,
  .columns {
    position: relative;
    padding-left: 0.9375em;
    padding-right: 0.9375em;
    float: left; }
```

This comes from the fact that the custom downloader submits the gutter as `em` instead of `rem`. I was able to get a custom download with the correct units by modifying the source of `marketing.js` on the fly with Chrome. The current source is:

```js
	$('#packageSubmit').on('click', function(e) {
		window.deps = [];
		// e.preventDefault();
		$('.pixel-value').each(function() {
			$(this).val($(this).val().split('px')[0]);
			$(this).val($(this).val() + 'px');
		});
		$('.em-value').each(function() {
			
			$(this).val($(this).val() + 'em');
		});
		$('.color-picker').each(function() {
			$(this).val('#' + $(this).val());
		});
```

It should be changed to:

```js
	$('#packageSubmit').on('click', function(e) {
		window.deps = [];
		// e.preventDefault();
		$('.pixel-value').each(function() {
			$(this).val($(this).val().split('px')[0]);
			$(this).val($(this).val() + 'px');
		});
		$('.em-value').each(function() {
			
			$(this).val($(this).val() + 'rem');
		});
		$('.color-picker').each(function() {
			$(this).val('#' + $(this).val());
		});
```

There's also a `setTimeout` to remove `em` from the value after the form has been submitted. That will need to be changed to `rem` as well.
