### ISSUE TITLE
Text going out of div columns

### ISSUE THREAD

**Issue by darkcyber** [zurb/foundation#6169]
here is the screenshoot of code
![Pict](http://img.prntscr.com/img?url=http://i.imgur.com/ngreCRA.png)

and here is the result
![Pict](http://img.prntscr.com/img?url=http://i.imgur.com/Pi51x9w.png)

How to fix it ? 

Thanks in advance.

**Comment by gakimball** [comment]
Web browsers won't wrap super long words like that ordinarily. If you're just trying to fill the space with placeholder text, I'd recommend using a site like [lipsum.org](http://lipsum.org/).

To actually change how text is wrapped, you need the text's container to be `overflow: hidden`, and then you can use the `text-overflow` property to affect what happens to the text when it spills off the edge.

```scss
.container {
  overflow: hidden;
  text-overflow: clip; // The default, it just disappears
  text-overflow: ellipsis; // Or, you can make an ellipsis (...) appear where the text is cut off
}
```

But since your text is one long string of characters with no spaces, the browser thinks it's one word, and so it can't actually wrap it.
