### ISSUE TITLE
Top Bar components not properly aligned

### ISSUE THREAD

**Issue by alexandrubau** [zurb/foundation#6202]
I use Safari 8.0.2 on Mac OS X and the Components from the Top Bar are not aligned properly in the provided documentation. Please see the search input and the submit button in the attached picture.

Thanks !  
  
![screen shot 2015-01-18 at 19 03 57](https://cloud.githubusercontent.com/assets/1225661/5793226/caedef2e-9f44-11e4-8070-e91829a6dfe8.png)

**Comment by gakimball** [comment]
This issue has come up before (#5533) and it's basically an issue of how browsers decide to round pixels. We got the variation between browsers to be within 1px of each other, so some browsers render it fine and some don't. That being said, we can definitely take another look.

**Comment by iacuzzoGiovanni** [comment]
+1 for this bug

**Comment by gakimball** [comment]
So the issue is still only in Safari. The issue is that top bar requires a few involved calculations to get the right heights and offsets of things, and then those odd values get converted to rems, giving you strange CSS like:

```scss
.top-bar input {
  height: 1.55556rem;
  top: 0.47222rem;
}
```

The browser then converts this back to pixels when it draws the page, and Safari is calculating the end result *slightly* differently than other browsers.

*So*, I think refactoring top bar too much may be risky, as it could end up being a breaking change. So instead, I wrote this CSS to override the default styles and line up everything properly. I tested it in every major browser and it all looks the same. This assumes you're using the default size of top bar, but if you aren't, it would be easy to change these values to match your design. Hope it helps! :)

```scss
@media #{$medium-up} {
  .top-bar {
    .button, input {
      display: block;
      font-size: 12px;
      height: 25px;
      line-height: 25px;
      padding: {
        top: 0;
        bottom: 0;
      }
    }
  }
}
```
