### ISSUE TITLE
Accordion Reflow:  bad width when responsive elements are included in the accordtion

### ISSUE THREAD

**Issue by vanboom** [zurb/foundation#6304]
In my case, I am using an accordion that contains slick slider components on the accordion content panels.  But the same issue exists with the Orbit slider. 

Suggestion:  control the visibility of the accordion panels using the height instead of display:none.

```css
// override the way the accordion panel visibility is handled.  Instead of setting display:none (which screws up embedded slick slider elements)
// set the height to 0, then auto to provide the same visibility toggle
.accordion .accordion-navigation > .content, .accordion dd > .content
{
  display: block;
  overflow-y: hidden;
  height: 0px;
  //padding: 0.9375rem;
  padding: 0;
}

.accordion .accordion-navigation > .content.active, .accordion dd > .content.active
{
  display: block;
  height: auto;
  background: #FFFFFF;
}
```
