### ISSUE TITLE
Remove color from headings?

### ISSUE THREAD

**Issue by kavonatsalv** [zurb/foundation#6390]
Foundation sets the color property on all heading tags to #222 (or the specified value of Body Font Color in custom builds).

Should this declaration exist?

Let's say we have a slider at the top of a page. Inside it sits both a `h1` and a `p` tag.

```html
<div class="slider">
	<h1>This is a heading</h1>
	<p>This is a paragraph</p>
</div>
```

The slider has a blue background, so we want all text inside it to be white.

```css
.slider {
	background: blue;
	color: white;
}
```

Our color declaration doesn't cascade through to all children. It works on paragraphs, but not headings as their color property is set by Foundation. Instead, we must be more explicit.

```css
.slider {
	background: blue;
	color: #fff;
}

.slider h1 { color: white; }
```

It's only a small issue, but one that has bugged me for years.

What are people's thoughts?
