### ISSUE TITLE
$accordion-navigation-active-font-color missing

### ISSUE THREAD

**Issue by andi1984** [zurb/foundation#6429]
Default Accordion Style based on current ```@mixin accordion-navigation```

```scss
> a {
   background: $bg;
   color: $font-color;
}
```

Active Accordion Style

```scss
&.#{ $active_class } > a {
   background: $active-bg;
}
```

Why can I change the active background color, but not the active font color?! Due to readability and color contrast it should be possible to adapt the active font color as well.

Please add a new variable like ```$accordion-navigation-active-font-color``` to tweak this functionality.
