### ISSUE TITLE
Invalid border-color in .postfix.button

### ISSUE THREAD

**Issue by ddanh85** [zurb/foundation#6546]
Here is an css output:
```css
.postfix.button {
  border-color: true;
}
```

The issue on the prefix too.

We can fix this by changes **postfix(false, false, true)** to **postfix($is-button:true)** in **.postfix.button** at line 408 in **_forms.scss** file.
