### ISSUE TITLE
$topbar-bottom-margin is overridden 

### ISSUE THREAD

**Issue by justinj656** [zurb/foundation#6552]
Hi, I am using foundation in rails, and my version is 5.5.2.1. 
I found setting $topbar-margin-bottom to some customerized is useless, because `margin-bottom: $topbar-margin-bottom` is overridden by `margin: 0 auto`
line 522 in ..components/_top-bar.scss
```scss
.contain-to-grid .top-bar {
        margin-bottom: $topbar-margin-bottom;
        margin: 0 auto;
        max-width: $row-width;
}
```
which will always lead to
```css
.contain-to-grid .top-bar {
    max-width: 62.5rem;
    margin: 0px auto;
}
```
Any idea ?
