### ISSUE TITLE
.button.hide not working

### ISSUE THREAD

**Issue by phaza** [zurb/foundation#6621]
When you apply `.hide`to a `.button` it doesn't work because https://github.com/zurb/foundation/blob/master/scss/foundation/components/_buttons.scss#L249 overrides the `display` value.

This is sufficient:
```CSS
.button.hide {
  display: none;
}
```
