### ISSUE TITLE
Create a mixin for callout-like panels

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6655]
So instead of having 1 colored panel for just callouts, I ended up trying to create all the normal color variations like you have for alerts. However, I was unable to use the `panel()` scss mixin because it's too bright, while the `.callout` panel is more muted and creates variations of CSS off of the primary color. It would be good if there was a `subpanel()` or something mixin, plus I have another issue open about creating the panel color variations.

This is what I ended up rolling myself:
```scss
@mixin subpanel($panel-color) {
  $panel-bg: scale-color($panel-color, $lightness: 94%);

  background: $panel-bg;
  border-color: scale-color($panel-bg, $lightness: -11%);

  a:not(.button) {
    color: $panel-color;

    &:hover,
    &:focus {
      color: scale-color($panel-color, $lightness: -14%);
    }
  }
}
```
