### ISSUE TITLE
The margin on the form fieldset legend is incorrectly ordered in 5.5.2

### ISSUE THREAD

**Issue by JamesJCole** [zurb/foundation#6685]
Currently the order is:
https://github.com/zurb/foundation/blob/master/scss/foundation/components/_forms.scss#L282-L283
```scss
    margin-#{$default-float}: rem-calc(-3);
    margin: 0;
```
should probably be:
```scss
    margin: 0;
    margin-#{$default-float}: rem-calc(-3);
```
If anyone can mention if this is intended and why, that would be great - otherwise i will setup a pull request to resolve it.
