### ISSUE TITLE
Reveal Modal Style Box Shadow _reveal.scss 

### ISSUE THREAD

**Issue by ricardo-lewis** [zurb/foundation#6857]
When you use the reveal-modal-style mixin, and set $box-shadow to false, it does not add a CSS rule to remove the box shadow.

Line 139 of _reveal.scss needs to be something like this:

```scss
  @if $box-shadow {
       box-shadow: $reveal-box-shadow;
  }@else{
       box-shadow: none;
  }

```
