### ISSUE TITLE
Documentation example for reveal-close mixin is incorrect

### ISSUE THREAD

**Issue by ricardo-lewis** [zurb/foundation#6858]
http://foundation.zurb.com/docs/components/reveal.html

This example does not work:
```SCSS
.custom-reveal-class {
  @include reveal-close(
    $color:$reveal-close-color
  );
}
```

It simply applies the Reveal Close button CSS to .custom-reveal-class.

This example works:
```SCSS
.custom-reveal-class {
  .#{$close-reveal-modal-class} { @include reveal-close; }
}
```
